version: "3.9"

services: 
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - ../data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../data/postgres/storage:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"