"""empty message

Revision ID: 3404f27bc06f
Revises: 91fc96a124a6
Create Date: 2023-07-12 15:23:42.862350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3404f27bc06f'
down_revision = '91fc96a124a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
